### ISSUE TITLE
SQL to migrate from tablemakerforcsv tablemaker

### ISSUE THREAD

**Issue by AlainRnet** [Gileba-org/mod_tablemaker#7]
Hello.
About your Note "you will need to create all modules again as there is no way to convert the tablemakerforcsv modules to a tablemaker module.", dont you think it's possible to make an SQL request to change all mod_tablemakerforcsv to mod_tablemaker ?

I tested on a test site and it seems to work pretty well : UPDATE `#__modules` SET `module` = 'mod_tablemaker' WHERE `__modules`.`module` = 'mod_tablemakerforcsv';

**Comment by Gileba** [comment]
Hi @AlainRnet 

I'll implement it in the next version, which I hope to release this week.

Kind regards
Gijs

**Comment by Gileba** [comment]
Implemented in #19

**Comment by AlainRnet** [comment]
It works very fine, thank you very much !
Do you know that on joomla extensions directory, this is not the last version ?

**Comment by Gileba** [comment]
The JED has been updated. Thanks.

**Comment by AlainRnet** [comment]
Thank you too.
I discovered your site, you could add a link to the documentation on the J! directory.

**Comment by AlainRnet** [comment]
But I don't understand why you need a download key or where to find it?!

**Comment by Gileba** [comment]
> Thank you too. I discovered your site, you could add a link to the documentation on the J! directory.

I thought I already did. The listing has been updated

**Comment by AlainRnet** [comment]
Sorry but I don't want to pay for a development that I participated to, even minimal. Can we find an arrangement?
